#!/bin/sh
############################################################
# This is a generic script to build any DixieApp that
# links libdixie.a
#
# usage:
# build_dixieapp <output_file> <input_file>...<input_file>
#
############################################################
#
outfile=$1
infiles=""
shift
while [ "$#" -gt "0" ]
do
    infiles="$infiles $1"
    shift
done 

if g++ $infiles -I$HOME/include -I. -L$HOME/lib -ldixie -o $outfile; then
    echo "Build complete -- run ./"$outfile" to verify"
else
    echo "***ERROR compiling $infiles"
fi
