#!/bin/bash
#############################################################
# Takes any number of words on the command line and checks  #
# if each one is the username of a user in our Hunter       #
# College network and then displays the username and the    #
# full name associated with it.                             #
#                                                           #
# Written by: Megan Williams on October 4, 2018             #
#                                                           #
# Usage: $0 <username> ...                                  #
#############################################################
# make sure there is a command line argument 
if [ $# -lt 2 ]
then
    echo "Usage: $0 <username_1> ... <username_n>"
    exit
fi

# loop until all parameters are used up
while [ $1 != "" ];
do
    if (grep $1 ypcat passwd)
        awk -F: ' $1 ~ /'$1'/ {print $5} ' $5
    # shift all the parameters down by one
    shift

done
